version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    working_directory: ~/project/Server
    docker:
      - image: cimg/node:17.2.0
      - image: circleci/mongo:4.2.0
    steps:
      - checkout:
          path: ~/project
      - node/install-npm
      - node/install-packages:
          app-dir: ~/project/Server
          cache-version: v1
          cache-path: node_modules
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project/Server
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build_and_test